Script: add site and source commands for yaml generation

diff --git a/cloudstate-antora b/cloudstate-antora
--- a/cloudstate-antora
+++ b/cloudstate-antora
@@ -69,17 +69,19 @@ function cloudstate_antora__help {
 cloudstate-antora build script
 
 Usage:
-  cloudstate-antora [command] [options]
+  cloudstate-antora <command> [<argument>...]
 
 Commands:
   build     Build a documentation site
   clean     Remove the build directory
   deploy    Deploy documentation to cloudstate.io
   preview   Run HTTP server to preview site
+  site      Create site configuration from source descriptors
+  source    Create source descriptor for a component
   validate  Validate xrefs across the site
   version   Describe version based on nearest git tag
 
-Use "cloudstate-antora help [command]" for more information about a command.
+Use "cloudstate-antora help <command>" for more information about a command.
 EOM
 }
 
@@ -88,25 +90,37 @@ function cloudstate_antora__help__build {
 Build a documentation site
 
 Usage:
-  cloudstate-antora build [options...] <playbook>
+  cloudstate-antora build [<option>...] <playbook>
+  cloudstate-antora build [<option>...] --site-from <source-descriptor>...
 
 Options:
   -a | --attribute <attribute|attribute=value>  Set an asciidoc attribute for site generation
        --author-mode                            Enable 'todo' and 'review' attributes
+  --site-from <source-descriptor>...            Use configuration generated by 'site' command
 EOM
 }
 
 function cloudstate_antora__build {
-  local playbook
+  local -a files
   local -a attributes
+  local site_from=false
+  local playbook
   while [[ $# -gt 0 ]] ; do
     case "$1" in
       --attribute | -a ) attributes+=("--attribute" "$2") ; shift 2 ;;
       --author-mode ) attributes+=("--attribute" "todo" "--attribute" "review") ; shift ;;
-      * ) playbook="$1" ; shift ;;
+      --site-from ) site_from=true ; shift ;;
+      * ) files+=("$1") ; shift ;;
     esac
   done
-  [ -z "$playbook" ] && fail "missing required argument: playbook"
+  if $site_from ; then
+    [ ${#files[@]} -eq 0 ] && fail "missing required argument: source-descriptor"
+    cloudstate_antora__site "${files[@]}"
+    playbook="build/site.yml"
+  else
+    playbook="${files[0]}"
+    [ -z "$playbook" ] && fail "missing required argument: playbook"
+  fi
   info "Building Antora documentation site..."
   docker run \
     -u $(id -u):$(id -g) \
@@ -115,8 +129,8 @@ function cloudstate_antora__build {
     --entrypoint /bin/sh \
     -t $antora_docker_image:$antora_version \
     -c "cd $base_dir && antora --cache-dir=.cache/antora --stacktrace ${attributes[@]} $playbook" \
-    || fail "Documentation site failed to build"
-  info $(green "Documentation site created") "$site_dir"
+    || fail "Failed to build documentation site"
+  info $(green "Created documentation site") "$site_dir"
 }
 
 function cloudstate_antora__help__clean {
@@ -138,7 +152,7 @@ function cloudstate_antora__help__deploy {
 Deploy documentation to cloudstate.io
 
 Usage:
-  cloudstate-antora deploy [options] <dirs...>
+  cloudstate-antora deploy [<option>...] <dir>...
 
 Options:
   -m | --module <module>      Name of this Cloudstate module (required)
@@ -214,15 +228,6 @@ function __deploy_push {
   fi
 }
 
-function __deploy_mkstring {
-  local prefix="$1"; shift
-  local delimiter="$1"; shift
-  local suffix="$1"; shift
-  local first="$1"; shift
-  local rest=("$@")
-  echo "${prefix}${first}${rest[@]/#/$delimiter}$suffix"
-}
-
 function cloudstate_antora__deploy {
   local module
   local upstream
@@ -259,20 +264,19 @@ function cloudstate_antora__deploy {
   rsync -av --delete --exclude='.git/' "$sources_dir/" "$upstream_repo_dir/"
 
   __deploy_push "$upstream" "$branch" "Update docs @ $commit"
+  local docs_commit=$(git -C "$upstream_repo_dir" log -1 '--format=format:%H')
 
   __deploy_checkout "$deploy_repository" "$deploy_branch"
   local docs_repo_dir=$(__deploy_repo_dir "$deploy_repository")
 
   local docs_sources_dir="$docs_repo_dir/sources"
   local docs_sources="$docs_sources_dir/$module.yml"
-  local start_paths=("${dirs[@]/#/$base_path/}")
   mkdir -p "$docs_sources_dir"
-  cat > $docs_sources <<EOF
-url: https://github.com/$upstream
-branches: [$branch]
-start_paths: $(__deploy_mkstring '[' ', ' ']' "${start_paths[@]}")
-edit_url: https://github.com/$upstream/edit/master/{path}
-EOF
+
+  cloudstate_antora__source -u "$upstream" -b "$branch" \
+    --comment "Docs for: https://github.com/$upstream/commit/$commit" \
+    --comment "Based on: https://github.com/$upstream/commit/$docs_commit" \
+    "${dirs[@]}" > "$docs_sources"
 
   # Note: concurrent deploys for different modules can conflict on push
   __deploy_push "$deploy_repository" "$deploy_branch"  "Deploy $module documentation: $upstream@$commit"
@@ -293,21 +297,143 @@ function cloudstate_antora__preview {
   python3 -m http.server --directory $site_dir
 }
 
+function cloudstate_antora__help__site {
+  cat <<EOM
+Create site configuration from source descriptors
+
+Usage:
+  cloudstate-antora site <source-descriptor>...
+EOM
+}
+
+function cloudstate_antora__site {
+  local sources=("$@")
+  [ ${#sources[@]} -eq 0 ] && fail "missing required argument: source-descriptor"
+
+  local site_yml="${build_dir}/site.yml"
+  mkdir -p "${build_dir}"
+  cat > $site_yml <<EOF
+site:
+  title: "Cloudstate Documentation"
+  url: https://cloudstate.io/docs/
+asciidoc:
+  attributes:
+    idprefix: ''
+    idseparator: '-'
+    page-pagination: '@'
+ui:
+  bundle:
+    url: https://github.com/cloudstateio/cloudstate-antora/raw/latest/download/ui-bundle.zip
+    snapshot: true
+runtime:
+  fetch: true
+output:
+  clean: true
+  dir: build/site
+content:
+  sources:
+EOF
+  local first=true
+  for source in "${sources[@]}" ; do
+    first=true
+    while read line ; do
+      if $first ; then
+        echo "  - $line" >> $site_yml
+        first=false
+      else
+        echo "    $line" >> $site_yml
+      fi
+    done < $source
+  done
+  info $(green "Created site configuration") $site_yml
+}
+
+function cloudstate_antora__help__source {
+  cat <<EOM
+Create source descriptor for a component
+
+Usage:
+  cloudstate-antora source [<option>...] <dir>...
+
+Options:
+  -u | --upstream <upstream>  Github upstream as <owner>/<repo> (required)
+  -b | --branch <branch>      Git branch to publish sources (required if not preview)
+  -p | --preview              Generate local preview source descriptor
+  -c | --comment <comment>    Add header comment to source descriptor
+EOM
+}
+
+function __source_mkstring {
+  local prefix="$1"; shift
+  local delimiter="$1"; shift
+  local suffix="$1"; shift
+  local first="$1"; shift
+  echo -n "$prefix"
+  echo -n "$first"
+  for element in "$@" ; do
+    echo -n "$delimiter$element"
+  done
+  echo "$suffix"
+}
+
+function cloudstate_antora__source {
+  local upstream
+  local branch
+  local preview=false
+  local -a comments
+  local -a dirs
+  while [[ $# -gt 0 ]] ; do
+    case "$1" in
+      --upstream | -u ) upstream="$2" ; shift 2 ;;
+      --branch | -b ) branch="$2" ; shift 2 ;;
+      --preview | -p ) preview=true ; shift ;;
+      --comment | -c ) comments+=("$2") ; shift 2 ;;
+      * ) dirs+=("$1") ; shift ;;
+    esac
+  done
+
+  [ -z "$upstream" ] && fail "missing required argument: upstream"
+  ! $preview && [ -z "$branch" ] && fail "missing required argument: branch"
+  [ ${#dirs[@]} -eq 0 ] && fail "missing required argument: dirs"
+
+  local url="https://github.com/$upstream"
+  local branches="[$branch]"
+  $preview && url="/antora" && branches="[HEAD]"
+  local start_dirs=("${dirs[@]/#/$base_path/}")
+  local start_paths=$(__source_mkstring '[' ', ' ']' "${start_dirs[@]}")
+  local edit_url="https://github.com/$upstream/edit/master/{path}"
+
+  for comment in "${comments[@]}" ; do
+    echo "# $comment"
+  done
+
+  cat <<EOF
+url: $url
+branches: $branches
+start_paths: $start_paths
+edit_url: $edit_url
+EOF
+}
+
 function cloudstate_antora__help__validate {
   cat <<EOM
 Validate xrefs or links across the site
 
 Usage:
-  cloudstate-antora validate [options...] [playbook]
+  cloudstate-antora validate [<option>...] <playbook>
+  cloudstate-antora validate [<option>...] --site-from <source-descriptor>...
 
 Options:
-  --links                  Whether to validate external links (with asciidoc-link-check)
-  --links-config <config>  Path to asciidoc-link-check config (within documentation dir)
-  --no-xrefs               Disable the xref validation (for only external link validation)
+  --links                             Whether to validate external links (with asciidoc-link-check)
+  --links-config <config>             Path to asciidoc-link-check config (within documentation dir)
+  --no-xrefs                          Disable the xref validation (for only external link validation)
+  --site-from <source-descriptor>...  Use configuration generated by 'site' command
 EOM
 }
 
 function cloudstate_antora__validate {
+  local -a files
+  local site_from=false
   local playbook
   local xrefs=true
   local links=false
@@ -317,19 +443,27 @@ function cloudstate_antora__validate {
       --links ) links=true ; shift ;;
       --links-config ) links_config="--config $2" ; shift 2 ;;
       --no-xrefs ) xrefs=false ; shift ;;
-      * ) playbook="$1" ; shift ;;
+      --site-from ) site_from=true ; shift ;;
+      * ) files+=("$1") ; shift ;;
     esac
   done
-  $xrefs && [ -z "$playbook" ] && fail "missing required argument: playbook"
   if $xrefs ; then
+    if $site_from ; then
+      [ ${#files[@]} -eq 0 ] && fail "missing required argument: source-descriptor"
+      cloudstate_antora__site "${files[@]}"
+      playbook="build/site.yml"
+    else
+      playbook="${files[0]}"
+      [ -z "$playbook" ] && fail "missing required argument: playbook"
+    fi
     docker run \
       -v "$root_dir:/antora" \
       --rm \
       --entrypoint /bin/sh \
       -t $antora_docker_image:$antora_version \
       -c "cd $base_dir && NODE_PATH=\"\$(npm -g root)\" antora --generator @antora/xref-validator $playbook" \
-      || fail "Documentation site failed to validate xrefs"
-    info $(green "Documentation site xrefs validated")
+      || fail "Failed to validate documentation xrefs"
+    info $(green "Validated documentation xrefs")
   fi
   # Note: variable substitution in links is not currently supported: https://github.com/gaurav-nelson/asciidoc-link-check/issues/16
   if $links ; then
@@ -339,8 +473,8 @@ function cloudstate_antora__validate {
       --entrypoint /bin/sh \
       -t $antora_docker_image:$antora_version \
       -c "cd $base_dir && find . -name '*.adoc' -print0 | xargs -0 -n1 asciidoc-link-check --progress $links_config" \
-      || fail "Documentation site failed to validate links"
-    info $(green "Documentation site links validated")
+      || fail "Failed to validate documentation links"
+    info $(green "Validated documentation links")
   fi
 }
 
@@ -349,7 +483,7 @@ function cloudstate_antora__help__version {
 Describe version based on nearest git tag
 
 Usage:
-  cloudstate-antora version [options]
+  cloudstate-antora version [<option>...]
 
 Options:
   --prefix <prefix>  Set the tag prefix (default: 'v')
